'use strict';

/**
 * External (non-CDP) browser kernels.
 *
 * Currently: Firefox-Reverse — a patched Firefox that carries its own AI
 * reverse-engineering agent in the C++ engine (JSVMP instruction trace, WASM
 * import boundary, engine-level branch diffing). Those live in SpiderMonkey and
 * have no CDP equivalent, which is the whole reason to support a second kernel.
 *
 * What AiBrowser does and does not do for this kernel:
 *   does     — isolated profile, process lifecycle, proxy prefs, Windows native-coordinate sync
 *   does not — fingerprint injection, CDP semantic tab sync, RPA, the CDP AI sidebar
 *
 * All of those ride on the Chrome DevTools Protocol, which Firefox does not
 * speak (it uses Marionette / WebDriver BiDi). Rather than half-wire them and
 * have them fail at runtime, `capabilities()` reports them off so the UI can
 * say so up front. Firefox-Reverse brings its own environment manager and
 * agent sidebar, so nothing is actually lost — it is a different product
 * running under the same launcher.
 */

const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const net = require('net');
const { spawn } = require('child_process');
const { parseProxy: parseProxyConfig } = require('../proxy-forwarder');

const KERNEL_ID = 'firefox-reverse';

/** Known install locations, most portable first. */
function candidateRoots(options = {}) {
  const roots = [];
  if (options.configuredPath) roots.push(String(options.configuredPath));
  if (options.userDataPath) roots.push(path.join(options.userDataPath, 'kernels', KERNEL_ID));
  if (options.appRoot) roots.push(path.join(options.appRoot, 'kernels', KERNEL_ID));
  return roots.filter(Boolean);
}

function binaryName() {
  if (process.platform === 'win32') return 'firefox.exe';
  if (process.platform === 'darwin') return path.join('Contents', 'MacOS', 'firefox');
  return 'firefox';
}

/** Resolve the kernel binary, or null when it is not installed. */
function detect(options = {}) {
  for (const root of candidateRoots(options)) {
    const resolved = path.resolve(root);
    const direct = path.join(resolved, binaryName());
    if (fs.existsSync(direct)) return { id: KERNEL_ID, root: resolved, binary: direct };
    // Allow pointing straight at the executable.
    if (/firefox(\.exe)?$/i.test(resolved) && fs.existsSync(resolved)) {
      return { id: KERNEL_ID, root: path.dirname(resolved), binary: resolved };
    }
  }
  return null;
}

/** What this kernel can and cannot do under AiBrowser. */
function capabilities() {
  return {
    id: KERNEL_ID,
    name: 'Firefox-Reverse',
    protocol: 'marionette',
    // Supported by AiBrowser
    isolatedProfile: true,
    processControl: true,
    proxy: true,
    windowSync: process.platform === 'win32',
    nativeCoordinateSync: process.platform === 'win32',
    semanticSync: false,
    // Not supported — these are CDP-only in this codebase
    cdp: false,
    fingerprintInjection: false,
    rpa: false,
    aiSidebar: false,
    note: 'Firefox 不支持 CDP：指纹注入、标签页语义同步、RPA 与内置 AI 侧边栏不可用；'
      + 'Windows 下支持原生坐标操作同步，并支持系统、HTTP 与 SOCKS 代理。',
  };
}

async function freePort(preferred = 0) {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.once('error', reject);
    server.listen(preferred, '127.0.0.1', () => {
      const { port } = server.address();
      server.close(() => resolve(port));
    });
  });
}

/**
 * Write the prefs Firefox reads at startup.
 * Marionette port has to come from a pref — the CLI flag only toggles it on.
 */
async function writeProfilePrefs(profileDir, { marionettePort, proxy, networkMode = 'direct' }) {
  const lines = [
    '// Generated by AiBrowser. Do not edit by hand.',
    'user_pref("browser.shell.checkDefaultBrowser", false);',
    'user_pref("browser.aboutwelcome.enabled", false);',
    'user_pref("datareporting.policy.dataSubmissionEnabled", false);',
    'user_pref("app.update.auto", false);',
  ];
  if (marionettePort) {
    lines.push('user_pref("marionette.port", ' + Number(marionettePort) + ');');
    lines.push('user_pref("marionette.enabled", true);');
  }
  const mode = networkMode === 'system' ? 'system' : (networkMode === 'proxy' ? 'proxy' : 'direct');
  const parsed = mode === 'proxy' ? parseProxy(proxy) : null;
  if (mode === 'proxy' && !parsed) throw new Error('Firefox 自定义代理地址不能为空');
  if (mode === 'system') {
    // Firefox value 5 delegates proxy discovery to the operating system.
    lines.push('user_pref("network.proxy.type", 5);');
  } else if (parsed) {
    lines.push('user_pref("network.proxy.type", 1);');
    // user.js is applied over persisted prefs.js. Reset every endpoint so an
    // earlier HTTP proxy cannot keep overriding a newly selected SOCKS proxy.
    for (const protocol of ['http', 'ssl', 'ftp', 'socks']) {
      lines.push(`user_pref("network.proxy.${protocol}", "");`);
      lines.push(`user_pref("network.proxy.${protocol}_port", 0);`);
    }
    lines.push('user_pref("network.proxy.no_proxies_on", "");');
    lines.push('user_pref("network.proxy.failover_direct", false);');
    lines.push('user_pref("network.proxy.share_proxy_settings", false);');
    if (parsed.scheme === 'socks') {
      lines.push(`user_pref("network.proxy.socks", "${parsed.host}");`);
      lines.push(`user_pref("network.proxy.socks_port", ${parsed.port});`);
      lines.push(`user_pref("network.proxy.socks_version", ${parsed.version});`);
      lines.push('user_pref("network.proxy.socks_remote_dns", true);');
    } else {
      lines.push(`user_pref("network.proxy.http", "${parsed.host}");`);
      lines.push(`user_pref("network.proxy.http_port", ${parsed.port});`);
      lines.push(`user_pref("network.proxy.ssl", "${parsed.host}");`);
      lines.push(`user_pref("network.proxy.ssl_port", ${parsed.port});`);
      lines.push('user_pref("network.proxy.share_proxy_settings", true);');
    }
  } else {
    // Always reset this preference. Otherwise prefs.js can retain an older
    // custom proxy after the environment is switched back to local direct.
    lines.push('user_pref("network.proxy.type", 0);');
  }
  await fsp.mkdir(profileDir, { recursive: true });
  await fsp.writeFile(path.join(profileDir, 'user.js'), lines.join('\n') + '\n', 'utf8');
}

function parseProxy(value) {
  const config = parseProxyConfig(value);
  if (!config) return null;
  // The engine converts these endpoints to an unauthenticated local HTTP
  // bridge. Silently discarding authentication/TLS here would use the wrong
  // transport or expose credentials to an unencrypted upstream connection.
  if (config.authenticated || config.protocol === 'https') {
    throw new Error('Firefox 认证或 HTTPS 代理必须通过本地代理转发器启动');
  }
  return {
    scheme: config.protocol.startsWith('socks') ? 'socks' : 'http',
    host: config.host,
    port: config.port,
    ...(config.protocol.startsWith('socks') ? { version: config.protocol === 'socks4' ? 4 : 5 } : {}),
  };
}

async function resolveBrowserWindowPid(launcherPid, timeoutMs = 15000) {
  if (process.platform !== 'win32') return launcherPid;
  const helper = path.join(__dirname, '..', 'native-browser-window-pid.exe');
  if (!fs.existsSync(helper)) return launcherPid;
  return new Promise((resolve) => {
    const child = spawn(helper, [String(launcherPid), String(timeoutMs)], { windowsHide: true, stdio: ['ignore', 'pipe', 'ignore'] });
    let output = '';
    const timer = setTimeout(() => { try { child.kill(); } catch (_) {} resolve(launcherPid); }, timeoutMs + 1200);
    child.stdout.setEncoding('utf8');
    child.stdout.on('data', (chunk) => { output += chunk; });
    child.once('error', () => { clearTimeout(timer); resolve(launcherPid); });
    child.once('exit', (code) => {
      clearTimeout(timer);
      const pid = Number.parseInt(output.trim(), 10);
      resolve(code === 0 && Number.isInteger(pid) && pid > 0 ? pid : launcherPid);
    });
  });
}

/**
 * Launch one environment on this kernel.
 * Returns { child, pid, profileDir, marionettePort } — no CDP port, by design.
 */
async function launch({ binary, profileDir, url, proxy, networkMode, marionettePort, env } = {}) {
  if (!binary || !fs.existsSync(binary)) throw new Error('Firefox-Reverse 内核不存在：' + binary);
  const port = Number(marionettePort) || await freePort(0);
  await writeProfilePrefs(profileDir, { marionettePort: port, proxy, networkMode });

  const args = ['-profile', profileDir, '-no-remote', '-marionette'];
  if (url) args.push(String(url));

  const child = spawn(binary, args, {
    detached: process.platform !== 'win32',
    windowsHide: false,
    stdio: ['ignore', 'pipe', 'pipe'],
    cwd: path.dirname(binary),
    env: env || process.env,
  });
  // spawn errors are asynchronous (e.g. an existing non-executable file).
  // Reject launch before the engine creates a running record for this child.
  await new Promise((resolve, reject) => {
    child.once('error', reject);
    child.once('spawn', resolve);
  });
  const launcherPid = child.pid;
  const pid = await resolveBrowserWindowPid(launcherPid);
  return { child, pid, launcherPid, profileDir, marionettePort: port };
}

/** Marionette is ready once the port accepts a connection. */
async function waitForMarionette(port, timeoutMs = 45000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const open = await new Promise((resolve) => {
      const socket = net.connect({ host: '127.0.0.1', port }, () => {
        socket.destroy();
        resolve(true);
      });
      socket.once('error', () => resolve(false));
      socket.setTimeout(1200, () => { socket.destroy(); resolve(false); });
    });
    if (open) return true;
    await new Promise((resolve) => setTimeout(resolve, 400));
  }
  return false;
}

module.exports = {
  KERNEL_ID,
  detect,
  capabilities,
  launch,
  waitForMarionette,
  writeProfilePrefs,
  parseProxy,
  resolveBrowserWindowPid,
  candidateRoots,
};
